stages:
  - phpstan
  - test

phpstan:
  image: jakzal/phpqa
  script: phpstan analyse --level 2 -c ./ci/phpstan.neon app
  allow_failure: true

before_script:
  - bash ci/docker_install.sh > /dev/null
  
test:8.0:
  image: php:8.0
  script:
    - phpunit --configuration phpunit_myapp.xml