version: '3.1'
services:
  db:
    image: "mysql:5.6"
    container_name: "db_container"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  web:
    build: ./.docker/apache
    container_name: "apache_container"
    env_file:
      - ./.env
    depends_on:
      - php
      - db
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    environment:
      APACHE_DOCUMENT_ROOT: "/var/www/html/public"

  php:
    image: php:8.0-fpm
    container_name: "php_container"
    volumes:
      - .:/var/www/html/

  composer:
    image: composer:2.1.8
    container_name: "composer_container"
    volumes:
      - .:/app
    command: bash -c "composer install && composer update"

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8000:80"